### PR TITLE
Update Travis CI

### PR DESCRIPTION
**Pull request by shivan1b**
Add up the before_install dependencies and their build procedure in the
following scripts:

install_ArduinoJson.sh - Contains build procedure of ArduinoJson library.

install_libical.sh - Contains the build procedure of libical.

install_wolfssl.sh - Contains the build procedure of wolfssl.

All the build procedures are common to *nix systems.
The idea of writing shell scripts for installation of different
libraries comes from the documentation here:
https://docs.travis-ci.com/user/installing-dependencies/

Closes Travis CI integration #6.

### CODE REVIEW

**Comment by elalfer** [comment]
Now you can see the error details @ https://travis-ci.org/elalfer/IoT-Cronus/jobs/167126751
I'm not sure if you suppose to do it without `./` or add exec permission to script files.

**Comment by shivan1b** [comment]
Sorry about this recent Revert mess. From what I could understand, the checks failed because Travis could not find the scripts at all. According to https://docs.travis-ci.com/user/installing-dependencies/ the scripts first need to be added to repository then Travis is going to work with those scripts. Should we try first adding up the scripts? Or should I write the content of scripts directly into Travis configuration? Please let me know what do you prefer. :)

**Comment by elalfer** [comment]
Hello. No worries. I think you did it correct and files were in the repo. Error message saw `permission denied` so there are some other issues happened. All configuration in the travis config file is fine for me as well.
Thanks again for your help

**Comment by elalfer** [comment]
I guess there are no need to install gcc through apt-get if it is specified in the requirements. Not sure why are you trying to install clang...

**Pull request closed without merging**
